/**
 * TagsPanel — displays AI-generated tags as clickable colored chips.
 */

import { motion, AnimatePresence } from 'framer-motion';
import { useQuery } from '@tanstack/react-query';
import { Tag, Hash } from 'lucide-react';
import { documentService } from '@/services/documentService';

interface Props {
  documentId: string;
}

// Deterministic color assignment based on tag name
const TAG_COLORS = [
  'bg-brand-100 text-brand-700 border-brand-200 hover:bg-brand-200 dark:bg-brand-950/40 dark:text-brand-300 dark:border-brand-800',
  'bg-accent-100 text-accent-700 border-accent-200 hover:bg-accent-200 dark:bg-accent-950/40 dark:text-accent-300 dark:border-accent-800',
  'bg-emerald-100 text-emerald-700 border-emerald-200 hover:bg-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-800',
  'bg-amber-100 text-amber-700 border-amber-200 hover:bg-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:border-amber-800',
  'bg-rose-100 text-rose-700 border-rose-200 hover:bg-rose-200 dark:bg-rose-950/40 dark:text-rose-300 dark:border-rose-800',
  'bg-teal-100 text-teal-700 border-teal-200 hover:bg-teal-200 dark:bg-teal-950/40 dark:text-teal-300 dark:border-teal-800',
  'bg-purple-100 text-purple-700 border-purple-200 hover:bg-purple-200 dark:bg-purple-950/40 dark:text-purple-300 dark:border-purple-800',
  'bg-orange-100 text-orange-700 border-orange-200 hover:bg-orange-200 dark:bg-orange-950/40 dark:text-orange-300 dark:border-orange-800',
];

function tagColor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) hash = (hash * 31 + name.charCodeAt(i)) >>> 0;
  return TAG_COLORS[hash % TAG_COLORS.length];
}

function Skeleton() {
  return (
    <div className="flex flex-wrap gap-2 animate-pulse">
      {[80, 64, 96, 72, 88, 60].map((w, i) => (
        <div
          key={i}
          className="h-8 rounded-full bg-surface-100 dark:bg-surface-800"
          style={{ width: `${w}px` }}
        />
      ))}
    </div>
  );
}

export function TagsPanel({ documentId }: Props) {
  const { data, isLoading } = useQuery({
    queryKey: ['ai-tags', documentId],
    queryFn: () => documentService.getAITags(documentId),
    staleTime: 60_000,
  });

  if (isLoading) return <Skeleton />;

  if (!data || data.tags.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center gap-4 py-16 text-center">
        <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-surface-100 dark:bg-surface-800">
          <Tag className="h-8 w-8 text-surface-400" />
        </div>
        <p className="text-sm text-surface-500">
          No tags yet — tags appear after AI processing completes.
        </p>
      </div>
    );
  }

  return (
    <AnimatePresence mode="wait">
      <motion.div
        key="tags"
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-5"
      >
        <p className="text-sm text-surface-500">
          {data.tags.length} tag{data.tags.length !== 1 ? 's' : ''} generated by AI
        </p>

        <div className="flex flex-wrap gap-2">
          {data.tags.map((tag, i) => (
            <motion.span
              key={tag.id}
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: i * 0.04 }}
              className={`inline-flex cursor-pointer items-center gap-1.5 rounded-full border px-3 py-1.5 text-sm font-medium transition-all ${tagColor(tag.name)}`}
            >
              <Hash className="h-3 w-3" />
              {tag.name}
            </motion.span>
          ))}
        </div>
      </motion.div>
    </AnimatePresence>
  );
}
